repos:

  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.7  # CURRENT_TAG/COMMIT_HASH
    hooks:
    - id: jupytext
      args: [--to, ipynb, --sync]
      files: \.ipynb$

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
      files: \.py$
        

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
    - id: nbqa
      args: [black]
      files: \.ipynb$  # Format .ipynb files
      additional_dependencies: [black==23.3.0]
